object Modules {
    const val FEATURE_WELCOME = ":feature:welcome"
    const val FEATURE_LOGIN = ":feature:login"
    const val FEATURE_REGISTER = ":feature:registration"
    const val FEATURE_HOME = ":feature:home"
    const val FEATURE_FORGOT_PASSWORD = ":feature:forgot_password"
    const val FEATURE_PROFILE = ":feature:profile"
    const val FEATURE_BOTTOM_SHEET = ":feature:image_bottom_sheet"
    const val FEATURE_SPLASH = ":feature:splash_screen"
    const val FEATURE_MATCH = ":feature:match"
    const val FEATURE_LIVE_MATCH_DETAILS = ":feature:live_match_details"
    const val FEATURE_SERIES = ":feature:series"
    const val FEATURE_TOURNAMENT = ":feature:tournament"
    const val FEATURE_TOURNAMENT_DETAILS = ":feature:tournament_details"
    const val FEATURE_CHATS = ":feature:chats"
    const val FEATURE_FRIEND_REQUEST = ":feature:friend_request"
    const val FEATURE_MESSAGE = ":feature:message"

    const val CORE_DATA = ":core:data"
    const val CORE_COMMON = ":core:common"
    const val CORE_DOMAIN = ":core:domain"
    const val CORE_UI = ":core-ui"
}