object ModulePackages {
    const val APP = "com.example.marketmingle"
    const val FEATURE_PROFILE = "com.example.profile"
    const val FEATURE_REGISTRATION = "com.example.registration"
    const val FEATURE_LOGIN = "com.example.login"
    const val FEATURE_SPLASH_SCREEN = "com.example.splash_screen"
    const val FEATURE_TOURNAMENT = "com.example.tournament"
    const val FEATURE_TOURNAMENT_DETAILS = "com.feature.tournament_details"
    const val FEATURE_WELCOME = "com.feature.welcome"
    const val FEATURE_SERIES = "com.feature.series"
    const val FEATURE_LIVE_MATCHES = "com.feature.live_matches"
    const val FEATURE_LIVE_MATCH_DETAILS = "com.feature.live_match_details"
    const val FEATURE_BOTTOM_SHEET = "com.example.image_bottom_sheet"
    const val FEATURE_HOME = "com.feature.home"
    const val FEATURE_FORGOT_PASSWORD = "com.example.forgot_password"
    const val FEATURE_MESSAGE = "com.example.message"
    const val CORE_DATA = "com.core.data"
    const val CORE_DOMAIN = "com.core.domain"
    const val CORE_COMMON = "com.core.common"
}